### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [2vek/hooktube-redirector#2]
Hi is it possible to see hooktube in dark colour (Grey like youtube) through this add on?

**Comment by 2vek** [comment]
Not really the purpose of this addon. 

You should ask swack (hooktube developer) for dark mode. His contact info is listed on header of website.

In meantime, you can use [this userstyle](https://userstyles.org/styles/147878/hooktube-dark-theme) or [few others](https://userstyles.org/styles/browse?search_terms=hooktube) with Stylish addon.
